default_language: cpp
theme: dracula

# Colors
background: "14"
foreground: "7"
primary_color: "#AFBEE1"
primary_color_subdued: "#084c61"
green: "#527251"
bright_green: "#BCE1AF"
bright_red: "#E49393"
red: "#A46060"
black: "#373B41"
gray: "240"
white: "#FFFFFF"
